### PR TITLE
Use a real browser

### LINKED ISSUE #27: Use Chrome instead of PhantomJS in Travis

### PR DESCRIPTION
**Pull request by martndemus**
closes #27

### CODE REVIEW

**Comment by poteto** [comment]
@homu r+

**Comment by bcardarella** [comment]
We should make this change across all of our ember addons

**Comment by martndemus** [comment]
@bcardarella I'll make the changes needed to the  add ons in some downtime.

**Comment by bcardarella** [comment]
:+1:

**Pull request merged**
