### PR TITLE
Added {{one-way-textarea}}

### PR DESCRIPTION
**Pull request by martndemus**
I have added a `<textarea>` element. I have extracted the code
from the `{{one-way-input}}` into a mixin to avoid duplication.

### CODE REVIEW

**Comment by kellyselden** [comment]
@martndemus I think this would be outside the scope of this project. I wouldn't expect any textarea functionality inside an input component wrapper. Although they would share a lot of the same code... Perhaps two repos with a common dependency that houses the mixin? Just thinking out loud.

**Comment by bcardarella** [comment]
If there is a desire I would advocate for a renaming of the project to `ember-one-way-controls` that can cover this use case for all of the html form controls that is reasonable.

**Comment by kellyselden** [comment]
@bcardarella Even better!

**Comment by martndemus** [comment]
Either way is fine, but I don't see why textarea is out of scope it is just a bigger input.

**Comment by rwjblue** [comment]
> I don't see why textarea is out of scope

Well, I believe the thought was referring to the name of the project: `ember-one-way-input` (inferring `<input>` element only).

But I'm game for making it a general purpose one way form control library as @bcardarella mentioned.

**Comment by martndemus** [comment]
Sure I'm game too, would be nice if all the one-way things came from one addon.

**Comment by poteto** [comment]
Yeah, `ember-one-way-controls` would be a nice addon that packaged together all the one way inputs/selects/radios/whatever. I'll see what free time I have to deprecate the old npm package and republish

**Comment by davidgoli** [comment]
:+1: any updates on this?

**Comment by davidgoli** [comment]
re: being out of scope, it's a meaningless, arbitrary fluke of HTML that `<textarea>` is its own element, while `<input type="checkbox">`, `<input type="text">`, `<input type="file">`, `<input type="image>` are all the same. In the meantime, this behavior is easy to override by supplying a `tagName` on the component like so:

```hbs
{{one-way-input
  tagName="textarea"
  ...
}}
```

**Comment by martndemus** [comment]
@homu r+

**Pull request merged**
