### PR TITLE
Support block expressions

### PR DESCRIPTION
**Pull request by tchak**
Needs more work on docs and I d'like to add more tests but I would love a first review. Do we agree on this change? If not, are there better options to achieve the use case?

### CODE REVIEW

**Comment by martndemus** [comment]
This looks good! 👍 
The only thing I don't like is the repeated if/else block in the one-way-select.hbs file. Can you look into cleaning that up a bit?

**Comment by tchak** [comment]
I think I am pretty happy with the current state :)

**Comment by martndemus** [comment]
Thanks!
@homu r+

**Comment by martndemus** [comment]
@tchak published in 0.8.0. I added in a bonus feature!

**Pull request merged**
