### PR TITLE
Made `ember-get-helper` optional, fixes #145

### LINKED ISSUE #145: Uncaught Error: Could not find module ember-metal/streams/utils
My Ember 2.11.0 app crashes with this error.

It is caused by the fact that `ember-one-way-controls` includes the [ember-get-helper](https://github.com/jmurphyau/ember-get-helper) addon, which is officially "deprecated and support for Ember 2.0 will not be maintained".

### PR DESCRIPTION
**Pull request by lolmaus**
`ember-one-way-controls` includes the `ember-get-helper` addon, which is [officially](https://github.com/jmurphyau/ember-get-helper) "deprecated and support for Ember 2.0 will not be maintained".

This PR makes `ember-get-helper` optional.

### CODE REVIEW

**Comment by rwjblue** [comment]
As mentioned in the linked issue: the correct fix is to update ember-get-helper so that it can properly noop on ember-source.

**Comment by ivanvanderbyl** [comment]
@rwjblue there's a [PR open](https://github.com/jmurphyau/ember-get-helper/pull/33) on ember-get-helper to fix this

**Comment by ivanvanderbyl** [comment]
It'd be great if we could get this merged.

**Comment by eshtadc** [comment]
This would also require removing the 1.13 test scenarios as they no longer work.  I tried playing around with using `ember-cli-version-checker` to conditionally add the `ember-get-helper` addon during installation based on the current version of Ember, but I couldn't get it to work with ember-try. Seems that given the drop in support it's not really a backwards compatible minor change, but a major one in terms of versioning.

**Comment by martndemus** [comment]
I'm closing this issue due to the fact that we have deprecated this addon. Check the [README](https://github.com/DockYard/ember-one-way-controls) for more info.

**Pull request closed without merging**
