### PR TITLE
action "update" called in own method

### PR DESCRIPTION
**Pull request by xcambar**
Hi,
I'd like to move the execution of `invokeAction(this, 'update', value)` from `_processNewValue` to its own method.

It doesn't break the behaviour of the inputs as it is not impactful on the flow of `_processNewValue`.
An advantage is that it allows to subclass the components and add new behaviours such as debouncing (my current use-case for this PR).

Hope you'll like it,

### CODE REVIEW

**Comment by xcambar** [comment]
FYI, the code for a debounced input:

```js
import Ember from 'ember';
import OneWayInput from 'ember-one-way-controls/components/one-way-input';

const {
  run: { debounce }
} = Ember;

export default OneWayInput.extend({
  debounceDelay: 500, // ms
  _updateNewValue(value) {
    debounce(this, this._super, value, this.get('debounceDelay'));
  }
});
```

**Comment by poteto** [comment]
I like this but I'll defer to @martndemus

**Comment by xcambar** [comment]
We could, but I didn't want to add up to the public API of the components.

**Comment by xcambar** [comment]
⚠️ DO NOT MERGE

Using the debounced example above does not work with a default value:

```hbs
<!-- WORKS-->
{{debounced-input update=(action (mut value))}}
<!-- DOES NOT WORK-->
{{debounced-input value update=(action (mut value))}}
```

I'll work on a fix.

**Comment by xcambar** [comment]
I've updated the debounced component code as follows, and now it works just fine:

```js
export default OneWayInput.extend({
  debounceDelay: 500, // ms
  _updateNewValue(value) {
    this.set('_value', value); // <-- here
    debounce(this, this._super, value, this.get('debounceDelay'));
  }
});
```

I'd like your input @poteto and @martndemus, I can't decide whether:
* the PR is safe, yet the debounced example has revealed hard to track inconsistencies
* the PR is unsafe
* whatever you think a third option could be 😄

**Comment by xcambar** [comment]
Is it worth rebasing?

ping @martndemus you haven't commented on the PR yet, as per @poteto 's request.

**Comment by xcambar** [comment]
Would you restart CircleCI, please?

**Comment by xcambar** [comment]
Any reason this PR remains dormant?

**Comment by martndemus** [comment]
I'm closing this issue due to the fact we have deprecated this addon. Check the [README](https://github.com/DockYard/ember-one-way-controls) for more info.

**Pull request closed without merging**
