### PR TITLE
Fixing Ember.Enumerable#contains deprecations

### PR DESCRIPTION
**Pull request by gmurphey**

### CODE REVIEW

**Comment by poteto** [comment]
Can you also add https://github.com/rwjblue/ember-runtime-enumerable-includes-polyfill please

**Comment by rwjblue** [comment]
👍 with that polyfill change

**Comment by gmurphey** [comment]
@poteto Good catch! Should be all set.

**Comment by martndemus** [comment]
@gmurphey needs rebae!

**Comment by martndemus** [comment]
Ah, whatever

**Pull request merged**
