### PR TITLE
WIP: failing test for options as an array of objects

### PR DESCRIPTION
**Pull request by GavinJoyce**

### CODE REVIEW

**Comment by martndemus** [comment]
Coincidentaly, I'm aware of this issue, and even more coincidentaly, I'm working on fixing it right now.

**Comment by GavinJoyce** [comment]
Coincidentaly² 

I was just about to dig into it, but I'll hold off for now. Please let me know if I can help with anything

**Comment by martndemus** [comment]
@GavinJoyce I've added the `optionTargetPath` property, this will give the select the behaviour you are seeking. See: https://github.com/DockYard/ember-one-way-controls/blob/master/docs/one-way-select.md#working-with-objects-instead-of-strings

**Comment by GavinJoyce** [comment]
@martndemus nice! thanks 🍻

**Pull request closed without merging**
