### PR TITLE
Prevent double rerender

### PR DESCRIPTION
**Pull request by knownasilya**
Not sure if this is the best solution, but I get the following:

> Assertion Failed: You modified "promptIsSelectable" twice on <mldp@component:form-fields/select-field::ember1630> in a single render. It was rendered in "component:one-way-select" and modified in "component:one-way-select". This was unreliable and slow in Ember 1.x and is no longer supported. See https://github.com/emberjs/ember.js/issues/13948 for more details.

Where `promptIsSelectable` isn't even set on my end.

### CODE REVIEW

**Comment by jamesdixon** [comment]
@knownasilya also getting this

**Comment by knownasilya** [comment]
Can we merge this, at least till there is a better solution?

**Comment by knownasilya** [comment]
Ping

**Comment by martndemus** [comment]
I'm closing this issue due to the fact that we have deprecated this addon. Check the [README](https://github.com/DockYard/ember-one-way-controls) for more info.

**Pull request closed without merging**
