### PR TITLE
Adds the binding of the maxlength attribute

### PR DESCRIPTION
**Pull request by panthony**
Adds binding for the 'maxlength' attribute of input

### CODE REVIEW

**Comment by john-griffin** [comment]
Just hit this, would be useful to support `maxlength`.

**Comment by davidgoli** [comment]
:+1: let's do it!

**Comment by davidgoli** [comment]
I get that https://github.com/dockyard/ember-one-way-controls/pull/22 is the "correct" way but it seems to be stalled, and I'm about to fork this repo to get this attribute for now. Can we just get this merged? The list of supported HTML input attributes is long but finite: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input#Attributes

**Comment by poteto** [comment]
@homu r+

**Pull request merged**
