### PR TITLE
Raise assertion when trying to use one-way-input with checkbox/radio type

### PR DESCRIPTION
**Pull request by martndemus**

### CODE REVIEW

**Comment by martndemus** [comment]
@homu r+

**Comment by kellyselden** [comment]
I'm not a fan of this. I use a dynamic type for switching between a checkbox list and a radio list on the fly to model relationships
https://github.com/kellyselden/ember-tree/blob/master/addon/templates/components/tree-node.hbs#L17

**Comment by martndemus** [comment]
Would a component that will polymorphically select the right component for you work?

**Comment by kellyselden** [comment]
I think so, as long as the `checked` vs `value` doesn't get in the way in this case, it should be fine.

**Pull request merged**
